[2024-05-19T13:24:30.630+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: fetch_parse_store_report_weather_data.send_report_to_telegram scheduled__2024-05-08T06:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
