[2024-05-26T00:23:42.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T00:23:42.915+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: integrate.load_local_db_to_postgres scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-26T00:23:42.973+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: integrate.load_local_db_to_postgres scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-26T00:23:42.975+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-26T00:23:43.034+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_local_db_to_postgres> on 2024-05-25 00:00:00+00:00
[2024-05-26T00:23:43.054+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9266) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T00:23:43.062+0000] {standard_task_runner.py:63} INFO - Started process 9278 to run task
[2024-05-26T00:23:43.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'integrate', 'load_local_db_to_postgres', 'scheduled__2024-05-25T00:00:00+00:00', '--job-id', '8696', '--raw', '--subdir', 'DAGS_FOLDER/integrate.py', '--cfg-path', '/tmp/tmpgru8bh36']
[2024-05-26T00:23:43.084+0000] {standard_task_runner.py:91} INFO - Job 8696: Subtask load_local_db_to_postgres
[2024-05-26T00:23:43.262+0000] {task_command.py:426} INFO - Running <TaskInstance: integrate.load_local_db_to_postgres scheduled__2024-05-25T00:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-26T00:23:43.620+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='integrate' AIRFLOW_CTX_TASK_ID='load_local_db_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:00:00+00:00'
[2024-05-26T00:23:43.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T00:23:43.626+0000] {logging_mixin.py:188} INFO - An error occurred: SQLite database file not found at path: /home/***/Desktop/local_database.db
[2024-05-26T00:23:43.627+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T00:23:43.628+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T00:23:43.662+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=integrate, task_id=load_local_db_to_postgres, execution_date=20240525T000000, start_date=20240526T002342, end_date=20240526T002343
[2024-05-26T00:23:43.737+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T00:23:44.155+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T00:23:44.192+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
