[2024-05-27T08:29:27.433+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T08:29:27.523+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-26T13:00:00+00:00 [queued]>
[2024-05-27T08:29:27.557+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-26T13:00:00+00:00 [queued]>
[2024-05-27T08:29:27.559+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-27T08:29:27.619+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-05-26 13:00:00+00:00
[2024-05-27T08:29:27.654+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=25085) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T08:29:27.660+0000] {standard_task_runner.py:63} INFO - Started process 25290 to run task
[2024-05-27T08:29:27.674+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'save_data_to_db', 'scheduled__2024-05-26T13:00:00+00:00', '--job-id', '12465', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmp2rfri68n']
[2024-05-27T08:29:27.677+0000] {standard_task_runner.py:91} INFO - Job 12465: Subtask save_data_to_db
[2024-05-27T08:29:27.868+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-26T13:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-27T08:29:28.211+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-26T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-26T13:00:00+00:00'
[2024-05-27T08:29:28.213+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T08:29:28.263+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-27T08:29:28.297+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.21.0.4), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-27T08:29:28.299+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T08:29:28.301+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T08:29:28.342+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_weather_data, task_id=save_data_to_db, execution_date=20240526T130000, start_date=20240527T082927, end_date=20240527T082928
[2024-05-27T08:29:28.458+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T08:29:28.867+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T08:29:28.892+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
