[2024-05-25T12:45:57.337+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T12:45:57.382+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-04-29T23:00:00+00:00 [queued]>
[2024-05-25T12:45:57.407+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-04-29T23:00:00+00:00 [queued]>
[2024-05-25T12:45:57.408+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-25T12:45:57.432+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-04-29 23:00:00+00:00
[2024-05-25T12:45:57.448+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5017) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T12:45:57.451+0000] {standard_task_runner.py:63} INFO - Started process 5119 to run task
[2024-05-25T12:45:57.452+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_forecast_weather_data', 'save_data_to_db', 'scheduled__2024-04-29T23:00:00+00:00', '--job-id', '8114', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmpq36862g0']
[2024-05-25T12:45:57.453+0000] {standard_task_runner.py:91} INFO - Job 8114: Subtask save_data_to_db
[2024-05-25T12:45:57.517+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-04-29T23:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-25T12:45:57.635+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_forecast_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T23:00:00+00:00'
[2024-05-25T12:45:57.637+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T12:45:57.649+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-25T12:45:57.653+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.21.0.2), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-25T12:45:57.653+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T12:45:57.654+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T12:45:57.666+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_forecast_weather_data, task_id=save_data_to_db, execution_date=20240429T230000, start_date=20240525T124557, end_date=20240525T124557
[2024-05-25T12:45:57.707+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T12:45:57.745+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-25T12:45:57.748+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
