[2024-05-18T10:30:51.332+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T10:30:51.364+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-16T01:00:00+00:00 [queued]>
[2024-05-18T10:30:51.377+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-16T01:00:00+00:00 [queued]>
[2024-05-18T10:30:51.378+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-18T10:30:51.398+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parse_cris_data> on 2024-05-16 01:00:00+00:00
[2024-05-18T10:30:51.408+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T10:30:51.410+0000] {standard_task_runner.py:63} INFO - Started process 202 to run task
[2024-05-18T10:30:51.410+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_parse_cris_data', 'parse_cris_data', 'scheduled__2024-05-16T01:00:00+00:00', '--job-id', '2709', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmprlfx5pt7']
[2024-05-18T10:30:51.413+0000] {standard_task_runner.py:91} INFO - Job 2709: Subtask parse_cris_data
[2024-05-18T10:30:51.470+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-16T01:00:00+00:00 [running]> on host e8691f41e037
[2024-05-18T10:30:51.603+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_parse_cris_data' AIRFLOW_CTX_TASK_ID='parse_cris_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T01:00:00+00:00'
[2024-05-18T10:30:51.605+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T10:30:51.606+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T10:30:51.607+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: parse_cris_data_and_save() missing 1 required positional argument: 'data'
[2024-05-18T10:30:51.616+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_parse_cris_data, task_id=parse_cris_data, execution_date=20240516T010000, start_date=20240518T103051, end_date=20240518T103051
[2024-05-18T10:30:51.632+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2709 for task parse_cris_data (parse_cris_data_and_save() missing 1 required positional argument: 'data'; 202)
[2024-05-18T10:30:51.665+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T10:30:51.695+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T10:30:51.702+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
