[2024-05-27T08:07:46.729+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T08:07:46.849+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-16T07:00:00+00:00 [queued]>
[2024-05-27T08:07:46.892+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-16T07:00:00+00:00 [queued]>
[2024-05-27T08:07:46.894+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-27T08:07:46.947+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-05-16 07:00:00+00:00
[2024-05-27T08:07:47.006+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=12951) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T08:07:47.014+0000] {standard_task_runner.py:63} INFO - Started process 13162 to run task
[2024-05-27T08:07:47.028+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'save_data_to_db', 'scheduled__2024-05-16T07:00:00+00:00', '--job-id', '11684', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmps59nl7vs']
[2024-05-27T08:07:47.062+0000] {standard_task_runner.py:91} INFO - Job 11684: Subtask save_data_to_db
[2024-05-27T08:07:47.273+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-16T07:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-27T08:07:47.653+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T07:00:00+00:00'
[2024-05-27T08:07:47.661+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T08:07:47.707+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-27T08:07:47.737+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.21.0.4), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-27T08:07:47.739+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T08:07:47.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T08:07:47.787+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_weather_data, task_id=save_data_to_db, execution_date=20240516T070000, start_date=20240527T080746, end_date=20240527T080747
[2024-05-27T08:07:47.895+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T08:07:48.089+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27T08:07:48.101+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
