[2024-05-19T12:03:39.120+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:03:39.167+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.generate_report scheduled__2024-04-30T03:00:00+00:00 [queued]>
[2024-05-19T12:03:39.183+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.generate_report scheduled__2024-04-30T03:00:00+00:00 [queued]>
[2024-05-19T12:03:39.185+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-19T12:03:39.218+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2024-04-30 03:00:00+00:00
[2024-05-19T12:03:39.231+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1563) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:03:39.233+0000] {standard_task_runner.py:63} INFO - Started process 1579 to run task
[2024-05-19T12:03:39.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'generate_report', 'scheduled__2024-04-30T03:00:00+00:00', '--job-id', '4973', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmps0qoxvtj']
[2024-05-19T12:03:39.239+0000] {standard_task_runner.py:91} INFO - Job 4973: Subtask generate_report
[2024-05-19T12:03:39.324+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.generate_report scheduled__2024-04-30T03:00:00+00:00 [running]> on host d2eb9883ca8d
[2024-05-19T12:03:39.893+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_weather_data' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T03:00:00+00:00'
[2024-05-19T12:03:39.901+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:03:39.922+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-19T12:03:39.930+0000] {logging_mixin.py:188} INFO - Error connecting to the database or fetching data: connection to server at "postgres" (172.18.0.5), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-19T12:03:39.931+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T12:03:39.932+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:03:39.952+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_weather_data, task_id=generate_report, execution_date=20240430T030000, start_date=20240519T120339, end_date=20240519T120339
[2024-05-19T12:03:40.181+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T12:03:40.237+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:03:40.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
