[2024-04-15T02:22:07.579+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T02:22:07.615+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_parse_weather_data.fetch_and_save_weather_data scheduled__2024-04-14T17:00:00+00:00 [queued]>
[2024-04-15T02:22:07.629+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_parse_weather_data.fetch_and_save_weather_data scheduled__2024-04-14T17:00:00+00:00 [queued]>
[2024-04-15T02:22:07.631+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-15T02:22:07.651+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_and_save_weather_data> on 2024-04-14 17:00:00+00:00
[2024-04-15T02:22:07.661+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T02:22:07.664+0000] {standard_task_runner.py:63} INFO - Started process 775 to run task
[2024-04-15T02:22:07.665+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_parse_weather_data', 'fetch_and_save_weather_data', 'scheduled__2024-04-14T17:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/json_dag.py', '--cfg-path', '/tmp/tmpw6u24kys']
[2024-04-15T02:22:07.669+0000] {standard_task_runner.py:91} INFO - Job 137: Subtask fetch_and_save_weather_data
[2024-04-15T02:22:07.733+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_parse_weather_data.fetch_and_save_weather_data scheduled__2024-04-14T17:00:00+00:00 [running]> on host 2c3c8df482d9
[2024-04-15T02:22:07.842+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_parse_weather_data' AIRFLOW_CTX_TASK_ID='fetch_and_save_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T17:00:00+00:00'
[2024-04-15T02:22:07.844+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T02:22:16.548+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T02:22:16.549+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/json_dag.py", line 24, in fetch_and_save_weather_data
    with open('C://Users/YtkaB/AppData/Roaming/JetBrains/PyCharm2024.1/scratches/output.json', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C://Users/YtkaB/AppData/Roaming/JetBrains/PyCharm2024.1/scratches/output.json'
[2024-04-15T02:22:16.561+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_parse_weather_data, task_id=fetch_and_save_weather_data, execution_date=20240414T170000, start_date=20240415T022207, end_date=20240415T022216
[2024-04-15T02:22:16.575+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 137 for task fetch_and_save_weather_data ([Errno 2] No such file or directory: 'C://Users/YtkaB/AppData/Roaming/JetBrains/PyCharm2024.1/scratches/output.json'; 775)
[2024-04-15T02:22:16.617+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T02:22:16.708+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T02:22:16.712+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-16T01:27:07.051+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T01:27:07.091+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_parse_weather_data.fetch_and_save_weather_data scheduled__2024-04-14T17:00:00+00:00 [queued]>
[2024-04-16T01:27:07.107+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_parse_weather_data.fetch_and_save_weather_data scheduled__2024-04-14T17:00:00+00:00 [queued]>
[2024-04-16T01:27:07.108+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T01:27:07.159+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_and_save_weather_data> on 2024-04-14 17:00:00+00:00
[2024-04-16T01:27:07.175+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=297) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T01:27:07.179+0000] {standard_task_runner.py:63} INFO - Started process 316 to run task
[2024-04-16T01:27:07.178+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_parse_weather_data', 'fetch_and_save_weather_data', 'scheduled__2024-04-14T17:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/json_dag.py', '--cfg-path', '/tmp/tmp14my6ytd']
[2024-04-16T01:27:07.185+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask fetch_and_save_weather_data
[2024-04-16T01:27:07.281+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_parse_weather_data.fetch_and_save_weather_data scheduled__2024-04-14T17:00:00+00:00 [running]> on host e8691f41e037
[2024-04-16T01:27:07.505+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_parse_weather_data' AIRFLOW_CTX_TASK_ID='fetch_and_save_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T17:00:00+00:00'
[2024-04-16T01:27:07.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T01:27:09.003+0000] {logging_mixin.py:188} INFO - Data has been successfully saved to the JSON file
[2024-04-16T01:27:09.005+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T01:27:09.007+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T01:27:09.030+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_and_parse_weather_data, task_id=fetch_and_save_weather_data, execution_date=20240414T170000, start_date=20240416T012707, end_date=20240416T012709
[2024-04-16T01:27:09.093+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T01:27:09.122+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T01:27:09.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
