[2024-05-27T08:19:15.777+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T08:19:15.822+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-22T10:00:00+00:00 [queued]>
[2024-05-27T08:19:15.841+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-22T10:00:00+00:00 [queued]>
[2024-05-27T08:19:15.843+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-27T08:19:15.870+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-05-22 10:00:00+00:00
[2024-05-27T08:19:15.897+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'save_data_to_db', 'scheduled__2024-05-22T10:00:00+00:00', '--job-id', '12057', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmp0h4qv457']
[2024-05-27T08:19:15.894+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=18997) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T08:19:15.901+0000] {standard_task_runner.py:91} INFO - Job 12057: Subtask save_data_to_db
[2024-05-27T08:19:15.902+0000] {standard_task_runner.py:63} INFO - Started process 19069 to run task
[2024-05-27T08:19:16.026+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-22T10:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-27T08:19:16.192+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-22T10:00:00+00:00'
[2024-05-27T08:19:16.194+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T08:19:16.211+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-27T08:19:16.217+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.21.0.4), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-27T08:19:16.218+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T08:19:16.219+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T08:19:16.236+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_weather_data, task_id=save_data_to_db, execution_date=20240522T100000, start_date=20240527T081915, end_date=20240527T081916
[2024-05-27T08:19:16.293+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T08:19:16.343+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27T08:19:16.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
