[2024-05-25T10:10:29.444+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T10:10:29.473+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-04-13T08:00:00+00:00 [queued]>
[2024-05-25T10:10:29.485+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-04-13T08:00:00+00:00 [queued]>
[2024-05-25T10:10:29.486+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-25T10:10:29.505+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-04-13 08:00:00+00:00
[2024-05-25T10:10:29.523+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_forecast_weather_data', 'save_data_to_db', 'scheduled__2024-04-13T08:00:00+00:00', '--job-id', '6478', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmp8tonk1c2']
[2024-05-25T10:10:29.522+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2936) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T10:10:29.524+0000] {standard_task_runner.py:91} INFO - Job 6478: Subtask save_data_to_db
[2024-05-25T10:10:29.525+0000] {standard_task_runner.py:63} INFO - Started process 2957 to run task
[2024-05-25T10:10:29.571+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-04-13T08:00:00+00:00 [running]> on host 9dd3157499a4
[2024-05-25T10:10:29.649+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_forecast_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T08:00:00+00:00'
[2024-05-25T10:10:29.650+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T10:10:29.658+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-25T10:10:29.661+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.18.0.3), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-25T10:10:29.661+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T10:10:29.662+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T10:10:29.670+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_forecast_weather_data, task_id=save_data_to_db, execution_date=20240413T080000, start_date=20240525T101029, end_date=20240525T101029
[2024-05-25T10:10:29.699+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T10:10:29.724+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-25T10:10:29.726+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
