[2024-05-19T12:52:38.142+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:52:38.193+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-05T08:00:00+00:00 [queued]>
[2024-05-19T12:52:38.215+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-05T08:00:00+00:00 [queued]>
[2024-05-19T12:52:38.217+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-19T12:52:38.251+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-05-05 08:00:00+00:00
[2024-05-19T12:52:38.270+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1498) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:52:38.277+0000] {standard_task_runner.py:63} INFO - Started process 1520 to run task
[2024-05-19T12:52:38.279+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'save_data_to_db', 'scheduled__2024-05-05T08:00:00+00:00', '--job-id', '5603', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmp20w8a0t6']
[2024-05-19T12:52:38.281+0000] {standard_task_runner.py:91} INFO - Job 5603: Subtask save_data_to_db
[2024-05-19T12:52:38.396+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.save_data_to_db scheduled__2024-05-05T08:00:00+00:00 [running]> on host d2eb9883ca8d
[2024-05-19T12:52:39.009+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-05T08:00:00+00:00'
[2024-05-19T12:52:39.014+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:52:39.036+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-19T12:52:39.042+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.18.0.5), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-19T12:52:39.044+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T12:52:39.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:52:39.062+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_weather_data, task_id=save_data_to_db, execution_date=20240505T080000, start_date=20240519T125238, end_date=20240519T125239
[2024-05-19T12:52:39.152+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T12:52:39.208+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:52:39.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
