[2024-05-27T08:15:44.563+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T08:15:44.661+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.generate_report scheduled__2024-05-18T21:00:00+00:00 [queued]>
[2024-05-27T08:15:44.732+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.generate_report scheduled__2024-05-18T21:00:00+00:00 [queued]>
[2024-05-27T08:15:44.745+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-27T08:15:44.796+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_report> on 2024-05-18 21:00:00+00:00
[2024-05-27T08:15:44.831+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=17088) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T08:15:44.834+0000] {standard_task_runner.py:63} INFO - Started process 17226 to run task
[2024-05-27T08:15:44.837+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'generate_report', 'scheduled__2024-05-18T21:00:00+00:00', '--job-id', '11937', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmpcvswdrj6']
[2024-05-27T08:15:44.858+0000] {standard_task_runner.py:91} INFO - Job 11937: Subtask generate_report
[2024-05-27T08:15:44.981+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.generate_report scheduled__2024-05-18T21:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-27T08:15:45.243+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_weather_data' AIRFLOW_CTX_TASK_ID='generate_report' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-18T21:00:00+00:00'
[2024-05-27T08:15:45.246+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T08:15:45.276+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-27T08:15:45.300+0000] {logging_mixin.py:188} INFO - Error connecting to the database or fetching data: connection to server at "postgres" (172.21.0.4), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-27T08:15:45.300+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T08:15:45.301+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T08:15:45.325+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_weather_data, task_id=generate_report, execution_date=20240518T210000, start_date=20240527T081544, end_date=20240527T081545
[2024-05-27T08:15:45.416+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T08:15:45.550+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27T08:15:45.568+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
