[2024-05-27T07:54:19.898+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T07:54:19.969+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.fetch_and_save_weather_data scheduled__2024-05-11T06:00:00+00:00 [queued]>
[2024-05-27T07:54:20.001+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_weather_data.fetch_and_save_weather_data scheduled__2024-05-11T06:00:00+00:00 [queued]>
[2024-05-27T07:54:20.003+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-27T07:54:20.062+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_and_save_weather_data> on 2024-05-11 06:00:00+00:00
[2024-05-27T07:54:20.115+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5225) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T07:54:20.117+0000] {standard_task_runner.py:63} INFO - Started process 5431 to run task
[2024-05-27T07:54:20.116+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_weather_data', 'fetch_and_save_weather_data', 'scheduled__2024-05-11T06:00:00+00:00', '--job-id', '11183', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmplv9o4m5e']
[2024-05-27T07:54:20.119+0000] {standard_task_runner.py:91} INFO - Job 11183: Subtask fetch_and_save_weather_data
[2024-05-27T07:54:20.355+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_weather_data.fetch_and_save_weather_data scheduled__2024-05-11T06:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-27T07:54:42.867+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11183 for task fetch_and_save_weather_data ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 5431)
[2024-05-27T07:54:43.860+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-27T07:54:43.956+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-27T07:54:43.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
