[2024-05-26T00:30:33.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T00:30:33.682+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-05-06T21:00:00+00:00 [queued]>
[2024-05-26T00:30:33.699+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-05-06T21:00:00+00:00 [queued]>
[2024-05-26T00:30:33.701+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-26T00:30:33.728+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): save_data_to_db> on 2024-05-06 21:00:00+00:00
[2024-05-26T00:30:33.746+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10757) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T00:30:33.749+0000] {standard_task_runner.py:63} INFO - Started process 10838 to run task
[2024-05-26T00:30:33.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_parse_store_report_forecast_weather_data', 'save_data_to_db', 'scheduled__2024-05-06T21:00:00+00:00', '--job-id', '8803', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmptnoyfz8l']
[2024-05-26T00:30:33.751+0000] {standard_task_runner.py:91} INFO - Job 8803: Subtask save_data_to_db
[2024-05-26T00:30:33.853+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_parse_store_report_forecast_weather_data.save_data_to_db scheduled__2024-05-06T21:00:00+00:00 [running]> on host b151419bfa2a
[2024-05-26T00:30:34.018+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_parse_store_report_forecast_weather_data' AIRFLOW_CTX_TASK_ID='save_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T21:00:00+00:00'
[2024-05-26T00:30:34.020+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T00:30:34.038+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-26T00:30:34.044+0000] {logging_mixin.py:188} INFO - Error connecting to the database: connection to server at "postgres" (172.21.0.2), port 5432 failed: FATAL:  database "weather_data" does not exist
[2024-05-26T00:30:34.045+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T00:30:34.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T00:30:34.064+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fetch_parse_store_report_forecast_weather_data, task_id=save_data_to_db, execution_date=20240506T210000, start_date=20240526T003033, end_date=20240526T003034
[2024-05-26T00:30:34.142+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T00:30:34.204+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-26T00:30:34.211+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
